
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/promotion?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: false

logging:
  level:
    com:
      yqkj:
        components:
          dtransaction: DEBUG
